// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA-tj9k342CfvWWFm-gm6Xc3jEx8T10uU',
    appId: '1:142916509182:web:81b45b6a7778c935e774af',
    messagingSenderId: '142916509182',
    projectId: 'animewatch-679b2',
    authDomain: 'animewatch-679b2.firebaseapp.com',
    storageBucket: 'animewatch-679b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQL48TBOl09EBDdBbziNFj819a2Umueeo',
    appId: '1:142916509182:android:bee6eda6f000f19ae774af',
    messagingSenderId: '142916509182',
    projectId: 'animewatch-679b2',
    storageBucket: 'animewatch-679b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnx9nITmPCkvh5iUPwoaSVnClULhp4fPU',
    appId: '1:142916509182:ios:d64ae57c6e3285dde774af',
    messagingSenderId: '142916509182',
    projectId: 'animewatch-679b2',
    storageBucket: 'animewatch-679b2.appspot.com',
    iosClientId: '142916509182-ittp4s04tkvc20o7c8j97cavor5f2gr5.apps.googleusercontent.com',
    iosBundleId: 'com.example.animewatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnx9nITmPCkvh5iUPwoaSVnClULhp4fPU',
    appId: '1:142916509182:ios:d64ae57c6e3285dde774af',
    messagingSenderId: '142916509182',
    projectId: 'animewatch-679b2',
    storageBucket: 'animewatch-679b2.appspot.com',
    iosClientId: '142916509182-ittp4s04tkvc20o7c8j97cavor5f2gr5.apps.googleusercontent.com',
    iosBundleId: 'com.example.animewatch',
  );
}
